create table brands (brand_id bigint generated by default as identity, company_name varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), primary key (brand_id))
create table categories (category_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), primary key (category_id))
create table keywords (keyword_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), key varchar(255), last_modified_date timestamp, last_modified_user varchar(255), value varchar(255), primary key (keyword_id))
create table payments (payment_id bigint generated by default as identity, active boolean, creation_date timestamp, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), payment_type varchar(255), primary key (payment_id))
create table product_categories (product_id bigint not null, category_id bigint not null)
create table product_keywords (product_id bigint not null, keyword_id bigint not null)
create table products (product_id bigint generated by default as identity, barcode varchar(255), creation_date timestamp, creation_user varchar(255), current_amount integer, current_price double, description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), brand_id bigint, primary key (product_id))
create table purchase_orders (purchase_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_date timestamp, purchase_order_number varchar(255), total_purchase_order_price double, payment_id bigint, supplier_id bigint, primary key (purchase_order_id))
create table purchase_orders_details (purchase_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_detail_date timestamp, quantity integer, total double, unit_price double, product_id bigint, purchase_order_id bigint, primary key (purchase_order_detail_id))
create table sale_orders (sale_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), sale_order_date timestamp, sale_order_number varchar(255), total_sale_order_price double, payment_id bigint, primary key (sale_order_id))
create table sale_orders_details (sale_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), quantity integer, sale_order_detail_date timestamp, total double, unit_price double, product_id bigint, sale_order_id bigint, primary key (sale_order_detail_id))
create table suppliers (supplier_id bigint generated by default as identity, address varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), email varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), phone_number1 varchar(255), phone_number2 varchar(255), primary key (supplier_id))
alter table product_categories add constraint FKd112rx0alycddsms029iifrih foreign key (category_id) references categories
alter table product_categories add constraint FKlda9rad6s180ha3dl1ncsp8n7 foreign key (product_id) references products
alter table product_keywords add constraint FKhikjayfb8l7ffwwhr6hscrlyp foreign key (keyword_id) references keywords
alter table product_keywords add constraint FK7ffcurtq0e3xfu7vophve5o2a foreign key (product_id) references products
alter table products add constraint FKa3a4mpsfdf4d2y6r8ra3sc8mv foreign key (brand_id) references brands
alter table purchase_orders add constraint FKfm5o2oqp00arh9866wjdp69ga foreign key (payment_id) references payments
alter table purchase_orders add constraint FKrpdasmb8y8xs5tiy4369xpinq foreign key (supplier_id) references suppliers
alter table purchase_orders_details add constraint FKndpxpgtjo5326fouj20gf7mv5 foreign key (product_id) references products
alter table purchase_orders_details add constraint FKfb8l4dpcontf0at9eyk22l1up foreign key (purchase_order_id) references purchase_orders
alter table sale_orders add constraint FKpiq88jcjrdtd4qoxo6jifqu31 foreign key (payment_id) references payments
alter table sale_orders_details add constraint FKfm7h6xl9356ek09b4px04pmb1 foreign key (product_id) references products
alter table sale_orders_details add constraint FKqs02h6876061qc852ykemdfmq foreign key (sale_order_id) references sale_orders
create sequence seq_product start with 100000000 increment by 50
create table brands (brand_id bigint generated by default as identity, company_name varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), primary key (brand_id))
create table categories (category_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), primary key (category_id))
create table keywords (keyword_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), key varchar(255), last_modified_date timestamp, last_modified_user varchar(255), value varchar(255), primary key (keyword_id))
create table payments (payment_id bigint generated by default as identity, active boolean, creation_date timestamp, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), payment_type varchar(255), primary key (payment_id))
create table product_categories (product_id bigint not null, category_id bigint not null)
create table product_keywords (product_id bigint not null, keyword_id bigint not null)
create table products (product_id bigint not null, barcode varchar(255), creation_date timestamp, creation_user varchar(255), current_amount integer, current_price double, description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), brand_id bigint, primary key (product_id))
create table purchase_orders (purchase_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_date timestamp, purchase_order_number varchar(255), total_purchase_order_price double, payment_id bigint, supplier_id bigint, primary key (purchase_order_id))
create table purchase_orders_details (purchase_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_detail_date timestamp, quantity integer, total double, unit_price double, product_id bigint, purchase_order_id bigint, primary key (purchase_order_detail_id))
create table sale_orders (sale_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), sale_order_date timestamp, sale_order_number varchar(255), total_sale_order_price double, payment_id bigint, primary key (sale_order_id))
create table sale_orders_details (sale_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), quantity integer, sale_order_detail_date timestamp, total double, unit_price double, product_id bigint, sale_order_id bigint, primary key (sale_order_detail_id))
create table suppliers (supplier_id bigint generated by default as identity, address varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), email varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), phone_number1 varchar(255), phone_number2 varchar(255), primary key (supplier_id))
alter table product_categories add constraint FKd112rx0alycddsms029iifrih foreign key (category_id) references categories
alter table product_categories add constraint FKlda9rad6s180ha3dl1ncsp8n7 foreign key (product_id) references products
alter table product_keywords add constraint FKhikjayfb8l7ffwwhr6hscrlyp foreign key (keyword_id) references keywords
alter table product_keywords add constraint FK7ffcurtq0e3xfu7vophve5o2a foreign key (product_id) references products
alter table products add constraint FKa3a4mpsfdf4d2y6r8ra3sc8mv foreign key (brand_id) references brands
alter table purchase_orders add constraint FKfm5o2oqp00arh9866wjdp69ga foreign key (payment_id) references payments
alter table purchase_orders add constraint FKrpdasmb8y8xs5tiy4369xpinq foreign key (supplier_id) references suppliers
alter table purchase_orders_details add constraint FKndpxpgtjo5326fouj20gf7mv5 foreign key (product_id) references products
alter table purchase_orders_details add constraint FKfb8l4dpcontf0at9eyk22l1up foreign key (purchase_order_id) references purchase_orders
alter table sale_orders add constraint FKpiq88jcjrdtd4qoxo6jifqu31 foreign key (payment_id) references payments
alter table sale_orders_details add constraint FKfm7h6xl9356ek09b4px04pmb1 foreign key (product_id) references products
alter table sale_orders_details add constraint FKqs02h6876061qc852ykemdfmq foreign key (sale_order_id) references sale_orders
create sequence seq_product start with 100000000 increment by 50
create table brands (brand_id bigint generated by default as identity, company_name varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), primary key (brand_id))
create table categories (category_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), primary key (category_id))
create table keywords (keyword_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), key varchar(255), last_modified_date timestamp, last_modified_user varchar(255), value varchar(255), primary key (keyword_id))
create table payments (payment_id bigint generated by default as identity, active boolean, creation_date timestamp, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), payment_type varchar(255), primary key (payment_id))
create table product_categories (product_id bigint not null, category_id bigint not null)
create table product_keywords (product_id bigint not null, keyword_id bigint not null)
create table products (product_id bigint not null, barcode varchar(255), creation_date timestamp, creation_user varchar(255), current_amount integer, current_price double, description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), brand_id bigint, primary key (product_id))
create table purchase_orders (purchase_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_date timestamp, purchase_order_number varchar(255), total_purchase_order_price double, payment_id bigint, supplier_id bigint, primary key (purchase_order_id))
create table purchase_orders_details (purchase_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_detail_date timestamp, quantity integer, total double, unit_price double, product_id bigint, purchase_order_id bigint, primary key (purchase_order_detail_id))
create table sale_orders (sale_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), sale_order_date timestamp, sale_order_number varchar(255), total_sale_order_price double, payment_id bigint, primary key (sale_order_id))
create table sale_orders_details (sale_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), quantity integer, sale_order_detail_date timestamp, total double, unit_price double, product_id bigint, sale_order_id bigint, primary key (sale_order_detail_id))
create table suppliers (supplier_id bigint generated by default as identity, address varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), email varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), phone_number1 varchar(255), phone_number2 varchar(255), primary key (supplier_id))
alter table product_categories add constraint FKd112rx0alycddsms029iifrih foreign key (category_id) references categories
alter table product_categories add constraint FKlda9rad6s180ha3dl1ncsp8n7 foreign key (product_id) references products
alter table product_keywords add constraint FKhikjayfb8l7ffwwhr6hscrlyp foreign key (keyword_id) references keywords
alter table product_keywords add constraint FK7ffcurtq0e3xfu7vophve5o2a foreign key (product_id) references products
alter table products add constraint FKa3a4mpsfdf4d2y6r8ra3sc8mv foreign key (brand_id) references brands
alter table purchase_orders add constraint FKfm5o2oqp00arh9866wjdp69ga foreign key (payment_id) references payments
alter table purchase_orders add constraint FKrpdasmb8y8xs5tiy4369xpinq foreign key (supplier_id) references suppliers
alter table purchase_orders_details add constraint FKndpxpgtjo5326fouj20gf7mv5 foreign key (product_id) references products
alter table purchase_orders_details add constraint FKfb8l4dpcontf0at9eyk22l1up foreign key (purchase_order_id) references purchase_orders
alter table sale_orders add constraint FKpiq88jcjrdtd4qoxo6jifqu31 foreign key (payment_id) references payments
alter table sale_orders_details add constraint FKfm7h6xl9356ek09b4px04pmb1 foreign key (product_id) references products
alter table sale_orders_details add constraint FKqs02h6876061qc852ykemdfmq foreign key (sale_order_id) references sale_orders
create sequence seq_product start with 100000000 increment by 1
create table brands (brand_id bigint generated by default as identity, company_name varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), primary key (brand_id))
create table categories (category_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), primary key (category_id))
create table keywords (keyword_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), key varchar(255), last_modified_date timestamp, last_modified_user varchar(255), value varchar(255), primary key (keyword_id))
create table payments (payment_id bigint generated by default as identity, active boolean, creation_date timestamp, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), payment_type varchar(255), primary key (payment_id))
create table product_categories (product_id bigint not null, category_id bigint not null)
create table product_keywords (product_id bigint not null, keyword_id bigint not null)
create table products (product_id bigint not null, barcode varchar(255), creation_date timestamp, creation_user varchar(255), current_amount integer, current_price double, description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), brand_id bigint, primary key (product_id))
create table purchase_orders (purchase_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_date timestamp, purchase_order_number varchar(255), total_purchase_order_price double, payment_id bigint, supplier_id bigint, primary key (purchase_order_id))
create table purchase_orders_details (purchase_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_detail_date timestamp, quantity integer, total double, unit_price double, product_id bigint, purchase_order_id bigint, primary key (purchase_order_detail_id))
create table sale_orders (sale_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), sale_order_date timestamp, sale_order_number varchar(255), total_sale_order_price double, payment_id bigint, primary key (sale_order_id))
create table sale_orders_details (sale_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), quantity integer, sale_order_detail_date timestamp, total double, unit_price double, product_id bigint, sale_order_id bigint, primary key (sale_order_detail_id))
create table suppliers (supplier_id bigint generated by default as identity, address varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), email varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), phone_number1 varchar(255), phone_number2 varchar(255), primary key (supplier_id))
alter table product_categories add constraint FKd112rx0alycddsms029iifrih foreign key (category_id) references categories
alter table product_categories add constraint FKlda9rad6s180ha3dl1ncsp8n7 foreign key (product_id) references products
alter table product_keywords add constraint FKhikjayfb8l7ffwwhr6hscrlyp foreign key (keyword_id) references keywords
alter table product_keywords add constraint FK7ffcurtq0e3xfu7vophve5o2a foreign key (product_id) references products
alter table products add constraint FKa3a4mpsfdf4d2y6r8ra3sc8mv foreign key (brand_id) references brands
alter table purchase_orders add constraint FKfm5o2oqp00arh9866wjdp69ga foreign key (payment_id) references payments
alter table purchase_orders add constraint FKrpdasmb8y8xs5tiy4369xpinq foreign key (supplier_id) references suppliers
alter table purchase_orders_details add constraint FKndpxpgtjo5326fouj20gf7mv5 foreign key (product_id) references products
alter table purchase_orders_details add constraint FKfb8l4dpcontf0at9eyk22l1up foreign key (purchase_order_id) references purchase_orders
alter table sale_orders add constraint FKpiq88jcjrdtd4qoxo6jifqu31 foreign key (payment_id) references payments
alter table sale_orders_details add constraint FKfm7h6xl9356ek09b4px04pmb1 foreign key (product_id) references products
alter table sale_orders_details add constraint FKqs02h6876061qc852ykemdfmq foreign key (sale_order_id) references sale_orders
create sequence seq_product start with 1 increment by 50
create table brands (brand_id bigint generated by default as identity, company_name varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), primary key (brand_id))
create table categories (category_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), primary key (category_id))
create table keywords (keyword_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), key varchar(255), last_modified_date timestamp, last_modified_user varchar(255), value varchar(255), primary key (keyword_id))
create table payments (payment_id bigint generated by default as identity, active boolean, creation_date timestamp, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), payment_type varchar(255), primary key (payment_id))
create table product_categories (product_id bigint not null, category_id bigint not null)
create table product_keywords (product_id bigint not null, keyword_id bigint not null)
create table products (product_id bigint not null, barcode varchar(255), creation_date timestamp, creation_user varchar(255), current_amount integer, current_price double, description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), brand_id bigint, primary key (product_id))
create table purchase_orders (purchase_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_date timestamp, purchase_order_number varchar(255), total_purchase_order_price double, payment_id bigint, supplier_id bigint, primary key (purchase_order_id))
create table purchase_orders_details (purchase_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_detail_date timestamp, quantity integer, total double, unit_price double, product_id bigint, purchase_order_id bigint, primary key (purchase_order_detail_id))
create table sale_orders (sale_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), sale_order_date timestamp, sale_order_number varchar(255), total_sale_order_price double, payment_id bigint, primary key (sale_order_id))
create table sale_orders_details (sale_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), quantity integer, sale_order_detail_date timestamp, total double, unit_price double, product_id bigint, sale_order_id bigint, primary key (sale_order_detail_id))
create table suppliers (supplier_id bigint generated by default as identity, address varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), email varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), phone_number1 varchar(255), phone_number2 varchar(255), primary key (supplier_id))
alter table product_categories add constraint FKd112rx0alycddsms029iifrih foreign key (category_id) references categories
alter table product_categories add constraint FKlda9rad6s180ha3dl1ncsp8n7 foreign key (product_id) references products
alter table product_keywords add constraint FKhikjayfb8l7ffwwhr6hscrlyp foreign key (keyword_id) references keywords
alter table product_keywords add constraint FK7ffcurtq0e3xfu7vophve5o2a foreign key (product_id) references products
alter table products add constraint FKa3a4mpsfdf4d2y6r8ra3sc8mv foreign key (brand_id) references brands
alter table purchase_orders add constraint FKfm5o2oqp00arh9866wjdp69ga foreign key (payment_id) references payments
alter table purchase_orders add constraint FKrpdasmb8y8xs5tiy4369xpinq foreign key (supplier_id) references suppliers
alter table purchase_orders_details add constraint FKndpxpgtjo5326fouj20gf7mv5 foreign key (product_id) references products
alter table purchase_orders_details add constraint FKfb8l4dpcontf0at9eyk22l1up foreign key (purchase_order_id) references purchase_orders
alter table sale_orders add constraint FKpiq88jcjrdtd4qoxo6jifqu31 foreign key (payment_id) references payments
alter table sale_orders_details add constraint FKfm7h6xl9356ek09b4px04pmb1 foreign key (product_id) references products
alter table sale_orders_details add constraint FKqs02h6876061qc852ykemdfmq foreign key (sale_order_id) references sale_orders
create sequence seq_product start with 1 increment by 1
create table brands (brand_id bigint generated by default as identity, company_name varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), primary key (brand_id))
create table categories (category_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), primary key (category_id))
create table keywords (keyword_id bigint generated by default as identity, creation_date timestamp, creation_user varchar(255), key varchar(255), last_modified_date timestamp, last_modified_user varchar(255), value varchar(255), primary key (keyword_id))
create table payments (payment_id bigint generated by default as identity, active boolean, creation_date timestamp, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), payment_type varchar(255), primary key (payment_id))
create table product_categories (product_id bigint not null, category_id bigint not null)
create table product_keywords (product_id bigint not null, keyword_id bigint not null)
create table products (product_id bigint not null, barcode varchar(255), creation_date timestamp, creation_user varchar(255), current_amount integer, current_price double, description varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), brand_id bigint, primary key (product_id))
create table purchase_orders (purchase_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_date timestamp, purchase_order_number varchar(255), total_purchase_order_price double, payment_id bigint, supplier_id bigint, primary key (purchase_order_id))
create table purchase_orders_details (purchase_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), purchase_order_detail_date timestamp, quantity integer, total double, unit_price double, product_id bigint, purchase_order_id bigint, primary key (purchase_order_detail_id))
create table sale_orders (sale_order_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), sale_order_date timestamp, sale_order_number varchar(255), total_sale_order_price double, payment_id bigint, primary key (sale_order_id))
create table sale_orders_details (sale_order_detail_id bigint generated by default as identity, creation_user varchar(255), last_modified_date timestamp, last_modified_user varchar(255), quantity integer, sale_order_detail_date timestamp, total double, unit_price double, product_id bigint, sale_order_id bigint, primary key (sale_order_detail_id))
create table suppliers (supplier_id bigint generated by default as identity, address varchar(255), creation_date timestamp, creation_user varchar(255), description varchar(255), email varchar(255), last_modified_date timestamp, last_modified_user varchar(255), name varchar(255), phone_number1 varchar(255), phone_number2 varchar(255), primary key (supplier_id))
alter table product_categories add constraint FKd112rx0alycddsms029iifrih foreign key (category_id) references categories
alter table product_categories add constraint FKlda9rad6s180ha3dl1ncsp8n7 foreign key (product_id) references products
alter table product_keywords add constraint FKhikjayfb8l7ffwwhr6hscrlyp foreign key (keyword_id) references keywords
alter table product_keywords add constraint FK7ffcurtq0e3xfu7vophve5o2a foreign key (product_id) references products
alter table products add constraint FKa3a4mpsfdf4d2y6r8ra3sc8mv foreign key (brand_id) references brands
alter table purchase_orders add constraint FKfm5o2oqp00arh9866wjdp69ga foreign key (payment_id) references payments
alter table purchase_orders add constraint FKrpdasmb8y8xs5tiy4369xpinq foreign key (supplier_id) references suppliers
alter table purchase_orders_details add constraint FKndpxpgtjo5326fouj20gf7mv5 foreign key (product_id) references products
alter table purchase_orders_details add constraint FKfb8l4dpcontf0at9eyk22l1up foreign key (purchase_order_id) references purchase_orders
alter table sale_orders add constraint FKpiq88jcjrdtd4qoxo6jifqu31 foreign key (payment_id) references payments
alter table sale_orders_details add constraint FKfm7h6xl9356ek09b4px04pmb1 foreign key (product_id) references products
alter table sale_orders_details add constraint FKqs02h6876061qc852ykemdfmq foreign key (sale_order_id) references sale_orders
